StatisticsMVC/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web;

namespace StatisticsMVC.Models
{
    public class Feedback
    {
        public string Name { get; set; }
       
        [DisplayName("Email Address")]
        public string EmailAddress { get; set; }

        [Required(ErrorMessage="Message is required.")]
        [DisplayName("Message *")]
        public string Message { get; set; }

         [DisplayName("Reply Requested")]
        public bool ReplyRequested { get; set; }

        public new string ToString()
        {
            var sb = new StringBuilder();
            sb.AppendLine("Date: "+ DateTime.Now.ToString("dd/MM/yyyy H:mm:ss"));
            sb.AppendLine("Name: " + Name);
            sb.AppendLine("Email Address:" + EmailAddress);
            if (ReplyRequested)
                sb.AppendLine("Reply Requested");
            sb.AppendLine("");
            sb.AppendLine(Message);
            sb.AppendLine("");

            return sb.ToString();
        }
    }
}

StatisticsMVC/Models/FileDataRepository.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace StatisticsMVC.Models
{
    public class FileDataRepository : IDataRepository
    {
        private String GetPath(string fileName)
        {
            return System.Web.HttpContext.Current.Server.MapPath("~/App_Data/" + fileName);
        }

        public string GetSampleData(string dataSet)
        {
            String dataFile;
            if (dataSet == "Movies")
            {
                dataFile = "movie_data.txt";
            }
            else if (dataSet == "Houses")
            {
                dataFile = "house_data.txt";
            }
            else
            {
                return string.Empty;
            }

            var path = GetPath(dataFile);
            string data;
            using (var sr = new StreamReader(path))
            {
                data = sr.ReadToEnd();
            }
            return data;
        }

        public void AddFeedback(Feedback feedback)
        {
            var path = GetPath("feedback.txt");
            using (var sw = new StreamWriter(path, true))
            {
                sw.WriteLine(feedback.ToString());
            }
        }
    }
}

StatisticsMVC/Models/IDataRepository.cs
using System;
namespace StatisticsMVC.Models
{
    interface IDataRepository
    {
        void AddFeedback(Feedback feedback);
        string GetSampleData(String dataSet);
    }
}

StatisticsMVC/Models/Log.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Configuration;

namespace StatisticsMVC.Models
{
    public class Log
    {
        private const string logFileName = "StatisticsLog.txt";

        private bool IsEnabled
        {
            get
            {
                  var setting = ConfigurationManager.AppSettings["EnableLogging"];
                  return (setting.ToUpper() == "TRUE" ? true : false);
            }
        }

        private String LogFilePath
        {
            get
            {
                return ConfigurationManager.AppSettings["LogFileLocation"];
            }
        }

        public void AddLogMessage(string location, string msg)
        {
            if (IsEnabled && !String.IsNullOrEmpty(LogFilePath))
            {
                if (Directory.Exists(LogFilePath))
                {
                    var logFile = LogFilePath + Path.DirectorySeparatorChar + logFileName;
                    var message = string.Format("{0}: [{1}] {2}", DateTime.Now.ToString("dd/MM/yyyy H:mm:ss"), location, msg);
                    try
                    {
                        using (var sw = new StreamWriter(logFile, true))
                        {
                            sw.WriteLine(message);
                        }

                    }
                    catch (Exception) { }
                }
               
            }
        }
    }
}

StatisticsMVC/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StatisticsMVC.Models;

namespace StatisticsMVC.Controllers
{
    public class StatisticsController : Controller
    {
        //
        // GET: /Statistics/
        public ActionResult Index()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("Index");
            return View();
        }

        // GET: /Statistics/BayesTheorem
        public ActionResult BayesTheorem()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("BayesTheorem");
            return View();
        }
        
        // GET: /Statistics/Estimators
        public ActionResult Estimators()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("Estimators");
            return View();
        }

        // GET: /Statistics/Regression
        public ActionResult Regression()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("Regression");
            return View();
        }

        // GET: /Statistics/Variance
        public ActionResult Variance()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("Variance");
            return View();
        }

        // GET: /Statistics/Probability
        public ActionResult Probability()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("Probability");
            return View();
        }

        // GET: /Statistics/GetData?dataset=Movies
        public ActionResult GetData(string dataSet)
        {
            var model = new FileDataRepository();
            var data = model.GetSampleData(dataSet);
            if (string.IsNullOrEmpty(data))
                return null;
            var result = Json(data, JsonRequestBehavior.AllowGet);
            return result;
        }

        //GET: /Statistics/FeedbackForm
        public ActionResult FeedbackForm()
        {
            ViewBag.LinkCss = LinkHelper.GenerateLinkClass("FeedbackForm");
            var model = new Feedback();
            return View(model);
        }

        // POST: /Statistics/FeedbackForm
        [HttpPost]
        public ActionResult FeedbackForm(Feedback info)
        {
            var model = new FileDataRepository();
            model.AddFeedback(info);
            return View("FeedbackResult", info);
        }

        // POST: /Statistics/AddLogMessage
        [HttpPost]
        public ActionResult AddLogMessage(string location, string message)
        {
            var model = new Log();
            model.AddLogMessage(location, message);
            return null;
        }

    }
}

StatisticsMVC/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

     @Styles.Render("~/Content/css/styles.css")
     @Scripts.Render("~/Content/lib/jquery/jquery-1.9.1.js")
     @Scripts.Render("~/Content/lib/jquery/jquery.validate.js")
     @Scripts.Render("~/Content/lib/jquery/jquery.validate.unobtrusive.js")
     @Scripts.Render("~/Content/lib/knockout/knockout-3.3.0.js")
     @Scripts.Render("~/Content/lib/d3/d3.min.js")
     @Scripts.Render("~/Content/lib/d3/d3-tip.js")
     @Scripts.Render("~/Content/app/logger.js")
    
</head>
    <body>
        <div id="topBar"><span>@ViewBag.Title</span>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Statistics",new object { },new { @class = @ViewBag.LinkCss["Index"]})</li>
                    <li>@Html.ActionLink("Variance", "Variance", "Statistics",new object { },new { @class = @ViewBag.LinkCss["Variance"]})</li>
                    <li>@Html.ActionLink("Probability", "Probability", "Statistics",new object { },new { @class = @ViewBag.LinkCss["Probability"]})</li>
                    <li>@Html.ActionLink("Bayes Theorem", "BayesTheorem", "Statistics",new object { },new { @class = @ViewBag.LinkCss["BayesTheorem"]})</li>
                    <li>@Html.ActionLink("Estimators", "Estimators", "Statistics",new object { },new { @class = @ViewBag.LinkCss["Estimators"]})</li>
                    <li>@Html.ActionLink("Regression", "Regression", "Statistics",new object { },new { @class = @ViewBag.LinkCss["Regression"]})</li>
                    <li>@Html.ActionLink("Feedback", "FeedbackForm", "Statistics",new object { },new { @class = @ViewBag.LinkCss["FeedbackForm"]})</li>
                </ul>
             </nav>
        </div>
        <div>
            @RenderBody()
        </div>
    </body>
</html>

StatisticsMVC/Views/Statistics/BayesTheorem.cshtml
@{
    ViewBag.Title = "Bayes Theorem";
}

<p>Bayes Theorem is a way of determining the probability of a something being true, given some evidence. An example of this is a screening test for a disease, such as a mammogram used to test for breast cancer. The probability of the screening test providing a positive result for a person who has the disease is known as the <strong>specificity</strong>. The probability of a test providing a negative result for a person who does not have the disease is known as the <strong>sensitivity</strong>. An ideal screening test has a high specificity (to reduce the number of false positives) and a high sensitivity (to reduce the number of false negatives). We can use Bayes Theorem to calculate the probability of a person having cancer when the screening test result is positive. The probability of a person having breast cancer will depend on variables, the most obvious being gender. For the purposes of this example we will use the following statistics: </p>
	
	<ul>
		<li>The chances of having breast cancer for women aged between 50 and 59 is 1 in 22, or 4.5% <sup><a class="references" href="http://www.cancerscreening.nhs.uk/breastscreen/breastcancer.html">[1]</a></sup>. This can be rephrased as (P|A)=0.045 where A = Breast Cancer. </li>
		<li>Sensitivity of the mammogram test is 67.8% <sup><a class="references" href="http://emedicine.medscape.com/article/1945498-overview">[2]</a></sup>. P(+|A) = 0.678</li>
		<li>Specificity of the mammogram test is 75%. P(-|!A) = 0.75</li>
	</ul>

	<p>Enter the figures in the table below to see the probability of the test returning a false negative or a false positive. The results might be surprising.</p>
	
	<p class="result" data-bind="visible: dataIsValid()">The chances of a <strong>true positive</strong> (the test providing a positive result when the person has the disease) is  <span data-bind="text: probTPPercentage"></span>%.</p> 
	
	<div class="section">
		<h2>Probability</h2>	
		<p>Enter values between 0 and 1 (eg for 30% enter 0.3):</p>
		<table>
			<tr>
				<td class="notation">P(A)</td>
				<td class="pdesc">Probability of A</td>
				<td class="data"><input type="text" size="5" data-bind="value: probA"></td>
			</tr>
			<tr>
				<td class="notation">P(+|A)</td>
				<td class="pdesc">Sensitivity</td>
				<td class="data"><input type="text" size="5" data-bind="value: sensitivity"></td>
			</tr>
			<tr>
				<td class="notation">P(-|!A)</td>
				<td class="pdesc">Specificity</td>
				<td class="data"><input type="text" size="5" data-bind="value: specificity"></td>
			</tr>
		</table>	 
	</div>
	
	 <div class="chart" data-bind="visible: dataIsValid()">
		<div id="pieChartA"></div>
	 </div>
	<div class="section" data-bind="visible: dataIsValid()">
		<h2>Results</h2>
		<table>
			<tr>
				<td class="notation">P(A|+)</td>
				<td class="pdesc">Probability of True Positive</td>
				<td><span data-bind="text: probTP"></span></td>
			</tr>
			<tr>
				<td class="notation">P(!A|+)</td>
				<td class="pdesc">Probability of False Positive</td>
				<td><span data-bind="text: probFP"></span></td>
			</tr>
			<tr>
				<td class="notation">P(!A|-)</td>
				<td class="pdesc">Probability of True Negative</td>
				<td><span data-bind="text: probTN"></span></td>
			</tr>
			<tr>
				<td class="notation">P(A|-)</td>
				<td class="pdesc">Probability of False Negative</td>
				<td><span data-bind="text: probFN"></span></td>
			</tr>
		</table>
	 </div>
	 
	 <div class="chart" data-bind="visible: dataIsValid()">
		<div id="pieChartTP"></div>
	 </div>
	 <div class="chart" data-bind="visible: dataIsValid()">
		<div id="pieChartTN"></div>
	 </div>
	 
	 <!-- This determines color of pie chart -->
	 <div id="pieColor1"></div>
	 <div id="pieColor2"></div>
	 
 @Scripts.Render("~/Content/charts/pieChart.js")
 @Scripts.Render("~/Content/app/bayesModel.js")
 @Scripts.Render("~/Content/app/bayes.js")

StatisticsMVC/Views/Statistics/Estimators.cshtml
@{
    ViewBag.Title = "Estimators";
}

<div>   
    <p>Number of rolls: 
			<input type="text" size="3" class="numberInput" data-bind="value: rolls">
			<button data-bind="click: rollTheDice">Roll</button>
		</p>
		
		<p class = "dice" data-bind="foreach : resultData">
			<span data-bind="text : $data"></span>
		</p>	
		
		<table id="EstimateTable">
			<thead>
				<tr>
					<th>Number</th>
					<th>Count</th>
					<th>Maximum Likelihood Estimate</th>
					<th>Laplacian Estimate</th>
				</tr>
			</thead>
			<tbody data-bind="foreach: estimates">
				<tr>
					<td class="dice"><span data-bind="text: number"></span></td>
				    <td><span data-bind="text: count"></span></td>
				    <td><span data-bind="text: mle"></span></td>
				    <td><span data-bind="text: le"></span></td>
				</tr>
			</tbody>
		</table>	 
	</div>
	
<div id="BarChartContainer" data-bind="visible: chartVisible">
    <div id="BarChart"></div>
    <div id="BarChartLegend" >
        <ul>
            <li><span class="bar1"></span>Maximum Likelihood Estimate</li>
            <li><span class="bar2"></span>Laplacian Estimate</li>
        </ul>
    </div>
</div>

 @Scripts.Render("~/Content/charts/barChart.js")
 @Scripts.Render("~/Content/app/estimate.js")
 @Scripts.Render("~/Content/app/estimatorsModel.js")
 @Scripts.Render("~/Content/app/estimators.js")

StatisticsMVC/Views/Statistics/FeedbackForm.cshtml
@model StatisticsMVC.Models.Feedback

@{
    ViewBag.Title = "Feedback Form";
}

<p>Please feel free to leave feedback. Name and email address are optional fields, and will only be used if you request a reply.</p>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Feedback</legend>
    
        <div class="feedbackLabel">@Html.LabelFor(model => model.Name)</div>
        <div class="feedbackField">@Html.TextBoxFor(model => model.Name)</div>
        <div class="feedbackLabel">@Html.LabelFor(model => model.EmailAddress)</div>
        <div class="feedbackField">@Html.TextBoxFor(model => model.EmailAddress)</div>
        <div class="feedbackLabel">@Html.LabelFor(model => model.Message)</div>
        <div class="feedbackField">@Html.TextAreaFor(model => model.Message,new {cols=40, rows=10})</div> 
        <div class="feedbackValid">@Html.ValidationMessageFor(model => model.Message)</div>   
        <div class="feedbackLabel">@Html.LabelFor(model => model.ReplyRequested)</div>
        <div class="feedbackField">@Html.CheckBoxFor(model => model.ReplyRequested)</div>
        
        <div class="feedbackSubmit"><input type="submit" value ="Submit" class="feedbackSubmit"/></div>

    </fieldset>
}

StatisticsMVC/Views/Statistics/FeedbackResult.cshtml
@model StatisticsMVC.Models.Feedback

@{
    ViewBag.Title = "Feedback Result";
}

<p>Thanks for taking the time to submit feedback!</p>
<div class="feedbackLabel">@Html.LabelFor(model => model.Name)</div>
<div class="feedbackField">@Html.DisplayFor(model => model.Name)</div>
<div class="feedbackLabel">@Html.LabelFor(model => model.EmailAddress)</div>
<div class="feedbackField">@Html.DisplayFor(model => model.EmailAddress)</div>
<div class="feedbackLabel">@Html.LabelFor(model => model.Message)</div>
<div class="feedbackField">@Html.DisplayFor(model => model.Message)</div>
<div class="feedbackLabel">@Html.LabelFor(model => model.ReplyRequested)</div>
<div class="feedbackField">@Html.DisplayFor(model => model.ReplyRequested)</div>
        

StatisticsMVC/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Statistics</h2>

<p>Interactive tools to visualise statistical methods.</p> 

<p>Inspired from the free Udacity course <a href="https://www.udacity.com/course/intro-to-statistics--st101">Statistics 101.</a></p>

StatisticsMVC/Views/Statistics/Probability.cshtml
@{
    ViewBag.Title = "Probability";
}

<p>Say we have a 6-sided dice... <span class = "dice">1 2 3 4 5 6</span> Assuming the dice is fair, there is an equal change of each result, so <span class="notationInText">P = 1/6</span>. </p>
<p>The opposite of the probaility is 1-P, so the probability of rolling something other than a <span class="dice">4</span> is:  <span class="notationInText">1-1/6 = 5/6</span>.</p>
<p>If we roll the dice three times what are the chances of getting <span class="dice">6</span> each time...? As each roll is an independent event the
    probabilities are multiplied.</p>

<table>
    <thead>
        <tr>
            <th>Roll 1</th>
            <th>Roll 2</th>
            <th>Roll 3</th>
            <th>P</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="dice">6</td> 
            <td class="dice">6</td> 
            <td class="dice">6</td> 
            <td class="notationData"> 1/6 * 1/6 * 1/6 = 0.005</td>
        </tr>
    </tbody>
</table>

<p>When there are multiple rolls of a dice we can build truth tables that give us all the possibilities. 
    In the above example there is only one case where each roll gives the same result. What if the question was - what are the chances
    of rolling the dice and getting a <span class="dice">6</span> two out of three times? Now there are multiple possibilities since the dice that is not a <span class="dice">6</span> 
    can be any of <span class="dice">1 2 3 4 5</span>. Also the result that is not a <span class="dice">6</span> could occur during any of the three rolls.
</p>
<p>The truth table contains all the possibilities:</p>

<div id="divBinomProbTruthTable">
<table>
    <thead>
        <tr>
            <th>Roll 1</th>
            <th>Roll 2</th>
            <th>Roll 3</th>
            <th>P</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: truthTable">
		<tr>
			<td class="dice"><span data-bind="text: roll1"></span></td>
			<td class="dice"><span data-bind="text: roll2"></span></td>
			<td class="dice"><span data-bind="text: roll3"></span></td>
			<td class="notationData"><span data-bind="text: p"></span></td>
		</tr>
	</tbody>
</table>
</div>

<div id="divBinomProb">
    <p>As you can see these truth tables grow big! We get 15 rows, and so the overall probability for this example is the sum of all the probabilities in the truth table.
       Which is <span class="notationInText"> 0.005 * 15  = 0.07</span>
        
     <p>There is a mathematical formula to generate this which is called the Binomial Probability</p>
    <p><span class="notationInText">b(x; n, P)</span> = <span class="notationInText">(n!/x!(n - x)!) * P^x * (1 - P)^n-x</span></p>
    <ul>
        <li> n is the total number of trials (we had 3 rolls)</li>
        <li>P is the probability of success of an individual trial (P=1/6) </li>
        <li>x is the number of successful results (x = 2)</li>
    </ul>
    <p><span class="notationInText">b(2; 3, 1/6)</span> = <span class="notationInText">(3!/2!(3 - 2)!) * (1/6)^3 * (1 - (1/6))^3-2</span> = <span class="notationInText"> 0.07</span></p>
    
    <p>Try it with different values:</p>
    <table>
    <thead>
        <tr>
            <th class="notation">n</th>
            <th class="notation">x</th>
            <th class="notation">P</th>
            <th class="notation">b(x; n, P)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="pdesc"><input type="text" size="5" data-bind="value: n"></td> 
            <td class="pdesc"><input type="text" size="5" data-bind="value: x"></td> 
            <td class="pdesc"><input type="text" size="5" data-bind="value: p"></td> 
            <td class="notationData"><span data-bind="text: result"></span></td>
        </tr>
    </tbody>
</table>

</div>

@Scripts.Render("~/Content/app/probabilityModel.js")
@Scripts.Render("~/Content/app/probability.js")

StatisticsMVC/Views/Statistics/Regression.cshtml
@{
    ViewBag.Title = "Regression";
}

<p>Choose a dataset and load the data. Changing the X and Y variables will plot the data on a scatter chart. The regression coefficient and r values are calculated.</p>
<p>
    <select id="dataset" data-bind="options: dataSetList, optionsText: $data, value: selectedDataSet"></select>
    <button id="btnLoadData" data-bind="click: LoadSampleData">Load Data</button>
</p>

   
<div id="divRegressionVariables" data-bind="visible: dataLoaded">
    <fieldset>
        <legend>Variables</legend>

        <p>Choose X Variable : <select id="xVariables" data-bind="options: variableListForCalc,
                                                                optionsText: 'display',
                                                                value: selectedVariableX,
                                                                event: { change: DoCalculation }">
                                </select>
        </p>
        <p>Choose Y Variable : <select id="yVariables" data-bind="options: variableListForCalc,
                                                            optionsText: 'display',
                                                            value: selectedVariableY,
                                                            event: { change: DoCalculation }">
                                </select>
        </p>
    </fieldset>
</div>

<div id="divRegressionValuesTable" data-bind="visible: dataLoaded">
    <table>
        <thead>
            <tr>
                <th class="notation">b</th>
                <th class="notation">a</th>
                <th class="notation">y = bx + a</th>
                <th class="notation">r</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="notationData"><span data-bind="text: valueB"></span></td>
                <td class="notationData"><span data-bind="text: valueA"></span></td>
                <td class="notationData"><span data-bind="text: lineEq"></span></td>
                <td class="notationData"><span data-bind="text: valueR"></span></td>
            </tr>
        </tbody>
    </table>	
    </div>
   
    <div id ="divRegressionScatterChart"></div> 


<div id ="divRegressionData" data-bind="visible: dataLoaded">
    <table id="DataTable">
        <thead>
            <tr data-bind="foreach: variableList">
                <th><span data-bind="text: $data.display"></span></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: dataItems">
            <tr data-bind="foreach: $parent.dataFields">
               <td data-bind="text: $parent[$data]"></td>
            </tr>
        </tbody>
    </table>	
</div>



@Scripts.Render("~/Content/charts/scatterChart.js")
@Scripts.Render("~/Content/app/movieData.js")
@Scripts.Render("~/Content/app/houseData.js")
@Scripts.Render("~/Content/app/regressionCalculation.js")
@Scripts.Render("~/Content/app/regression.js")

<script>
    $(document).ready(function () {

        var model = new RegressionModel();
        model.actionUrlGetData = "@Url.Action("GetData", "Statistics")";
        ko.applyBindings(model);

    });
</script>

StatisticsMVC/Views/Statistics/Variance.cshtml
@{
    ViewBag.Title = "Variance";
}

<p>This page deals with some of the most common statistics used: The mean, variance and standard deviation. 
    Choose a data set and then choose a variable to see the results. </p>

 <table>
     <tr>
         <td class="notation">Mean</td>
         <td class="pdesc">Mean</td>
         <td>Also known as the average. Calculated as the sum of the values in the data set divided by the number of items. </td>
     </tr>
     <tr>
         <td class="notation">Variance</td>
         <td class="pdesc">Variance</td>
         <td>Determines how individual items in a data set differ from the mean. 
             The variance of a population is calculated by first calculating the mean.
             Then for each item in the data set, calculate the difference from the mean. Square those results and sum them.
             Then divide this by the number of items.
         </td>
     </tr>
     <tr>
         <td class="notation">Std Dev</td>
         <td class="pdesc">Standard Deviation</td>
         <td>The standard deviation is calculated as the square root of the variance. </td>
     </tr>
    </table>	

<p>Choose dataset:
    <select id="dataset" data-bind="options: dataSetList, optionsText: $data, value: selectedDataSet"></select>
    <button id="btnLoadData" data-bind="click: LoadSampleData">Load Data</button>
</p>

<div id="divVarianceVariables" data-bind="visible: dataLoaded">
<p>Choose Variable : <select id="variables" data-bind="options: variableList,
                                                        optionsText: 'display',
                                                        value: selectedVariable,
                                                        event: { change: DoCalculation }">
                        </select>
</p>
</div>

<div id="divVarianceValuesTable" data-bind="visible: dataLoaded">
    <table>
        <thead>
            <tr>
                <th class="notation">Mean</th>
                <th class="notation">Variance</th>
                <th class="notation">Std Dev</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="notationData"><span data-bind="text: mean"></span></td>
                <td class="notationData"><span data-bind="text: variance"></span></td>
                <td class="notationData"><span data-bind="text: stddev"></span></td>
            </tr>
        </tbody>
    </table>	
    </div>

<div id ="divVarianceData" data-bind="visible: dataLoaded">
    <table id="DataTable">
        <thead>
            <tr data-bind="foreach: variableList">
                <th><span data-bind="text: $data.display"></span></th>
            </tr>
        </thead>
        <tbody data-bind="foreach: dataItems">
            <tr data-bind="foreach: $parent.dataFields">
               <td data-bind="text: $parent[$data]"></td>
            </tr>
        </tbody>
    </table>	
</div>


@Scripts.Render("~/Content/app/movieData.js")
@Scripts.Render("~/Content/app/houseData.js")
@Scripts.Render("~/Content/app/varianceCalculation.js")
@Scripts.Render("~/Content/app/variance.js")

<script>
    $(document).ready(function () {

        var model = new VarianceModel();
        model.actionUrlGetData = "@Url.Action("GetData", "Statistics")";
        ko.applyBindings(model);

    });
</script>